apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
  labels:
    app: react-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: react-app
  template:
    metadata:
      labels:
        app: react-app 
    spec:
      containers:
      - name: react-app
        image: venkatesh9722/react-app:latest
        ports:
        - containerPort: 3000